### ISSUE TITLE
Does not work on 32-bit devices

### ISSUE THREAD

**Issue by jsawruk** [jonasman/TeslaSwift#11]
I still have an iPad 4, which is a 32-bit device (iOS 10.3.2). I could not get it to connect to my vehicle when running on the device, but it worked on the simulator, which is 64 bit.

This happens because the datatype for Vehicle.id is Int instead of Int64. Fortunately, Vehicle.idS contains the string value of the 64-bit value.

To correct this, do the following:

In Vehicle.swift, change:
`open var id: Int?`
to
`open var id: Int64?`

Also change:
`id						<- map["id"]`
to
`id <- (map["id_s"], TransformOf<Int64, String>(fromJSON: { Int64($0!) }, toJSON: { $0.map { String($0) } }))`

In TeslaEndpoint.swift, change all the vehicleID parameters to Int64. For example, change:
`case command(vehicleID: Int, command:VehicleCommand)`
to
`case command(vehicleID: Int64, command:VehicleCommand)`

Doing this ensures that Vehicle.id is Int64 on both 32 and 64 bit architectures. Apple will probably phase out support for 32-bit devices by the end of the year, but since Swift can run on other platforms, it is probably a good idea to support 32-bit systems. 

If you want, I can create a pull request.

**Comment by jonasman** [comment]
Thanks for the heads up. Im on holiday. Can you PR the change?

**Comment by jonasman** [comment]
Another alternative is to just use a string Id as the endpoint will convert those int numbers to strings

**Comment by jsawruk** [comment]
I agree that String is the correct data type, since it's being passed to a URL anyway. I have modified the id field to read from the id_s field in the JSON response. I tested this and it works on my iPad. I am forking the code now and will submit the pull request shortly.
