### ISSUE TITLE
Mark 7.1.0 as a stable release

### ISSUE THREAD

**Issue by callumboddy** [jonasman/TeslaSwift#110]
Currently the latest stable release is 7.0.0 which doesn't contain the fixes required to build in Xcode 13.

I can't link my library to another project pointing to a stable version until TeslaSwift is marked as a stable version

```
Dependencies could not be resolved because root depends on '' 0.2.1..<0.3.0.
'' >= 0.2.1 cannot be used because package '' is required using a stable-version but '' depends on an unstable-version package 'teslaswift' and no versions of '' match the requirement 0.2.2..<0.3.0.
```

I have a short term workaround by linking to my framework pointing directly to the commit.

Thanks!

**Comment by jonasman** [comment]
where do we mark such a thing?

**Comment by callumboddy** [comment]
I can see you have already done it! thank you

**Comment by jonasman** [comment]
ok cool, it was the GitHub releases
