### ISSUE TITLE
401 on login

### ISSUE THREAD

**Issue by RSickenberg** [jonasman/TeslaSwift#113]
Hello, 

I'm digging into it but since few days, Tesla has changed how the token is treated.

Can you help on this? 
Regards

**Comment by jonasman** [comment]
seems like the auth was updated: https://github.com/timdorr/tesla-api/issues/548

Now there is one less step

**Comment by RSickenberg** [comment]
@jonasman Indeed, is this fixable on your side?

**Comment by jonasman** [comment]
I just tried and it works here, are you using web login?

**Comment by jonasman** [comment]
I guess my account is still on the old system, might need to wait intel i get the error

**Comment by jonasman** [comment]
I just checked and this API was already using the correct approach of step 3 only. Can you post some jsons here to see what is happening on your side?

**Comment by RSickenberg** [comment]
Need to dig, will update soon

**Comment by RSickenberg** [comment]
Ok so au reworked my app but it seems the token only lives for ~ 8h or so, do you have a technique to refresh it in the background?

**Comment by RSickenberg** [comment]
Hey @jonasman, since I'm not using 100% of the lib, I currently have issues with the `refreshWebToken` method. 

On the line: 
```swift
request(.oAuth2Token, body: body) { [weak self] (result: Result<AuthToken, Error>) in
            guard let self = self else { completion(Result.failure(TeslaError.internalError)); return }
``` 
I got the `guard` line that returns an internal method.

Here is my simple implementation: 
```swift
let api = TeslaSwift()

api.reuse(token: trueToken)
api.refreshWebToken { result in
    completion(result)
}
```

Regards.

**Comment by RSickenberg** [comment]
Ok, this was my fault, I shouldn't init a new instance eachtime.
