### ISSUE TITLE
"Example on how to get a list of vehicles with promiseKit" error

### ISSUE THREAD

**Issue by sj10lon** [jonasman/TeslaSwift#120]
It's been a long time since I worked on this API, so I had to take a look. I am currently stuck on this one:

_Example on how to get a list of vehicles with promiseKit_

```
class CarsViewController: ViewController {
    func showCars() {
      do {
        let response = try await api.getVehicles()
        self.data = response
        self.tableView.reloadData()
      } catch let error {
        //Process error
     }
}
```

I get the following errors:
<img width="835" alt="image" src="https://user-images.githubusercontent.com/96663959/190929476-ba365cff-531b-45a1-8084-cdbf706db3a0.png">

What is the `getVehicles` function supposed to look like?

**Comment by jonasman** [comment]
are you on the wrong version of the API? 

you need the async await version

**Comment by sj10lon** [comment]
> are you on the wrong version of the API? you need the async await version

Don't think so(?) This is what my `Podfile` looks like:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyApp
  
  pod 'TeslaSwift'
  pod 'PromiseKit'
  
end
```

**Comment by sj10lon** [comment]
Ok so I managed to get it working by doing this:
`pod 'TeslaSwift', :git => 'https://github.com/jonasman/TeslaSwift.git', :tag => '8.0.0'`

But the await func does not work. I have it like this in the FirstViewController:

```
func viewDidLoad() async {
        super.viewDidLoad()
        print("print?")
        await getVehicles()
    }
```
    func viewDidAppear(_ animated: Bool) async {
        print("print?")
        await getVehicles()
    }
```
func getVehicles() async {
        do {
            let response = try await api.getVehicles()
            self.data = response
            self.collectionView.reloadData()
            print(response)
        } catch let error {
            //Process error
            print("error: \(error)")
        }
    }
```

I tried with both viewDidLoad and viewDidAppear, but none of them are running when using async and await. They do not run the print either..
