### ISSUE TITLE
completion handler?

### ISSUE THREAD

**Issue by sj10lon** [jonasman/TeslaSwift#121]
How do I add a completion handler to tell the user the action was successfully done or to display any error that may occur?

This is the current function I have:

```
func climateOn() {
    Task { @MainActor in
        _ = try await api.sendCommandToVehicle(vehicle!, command: VehicleCommand.startAutoConditioning)
    }
}
```

**Comment by jonasman** [comment]
func climateOn() {
    Task { @MainActor in
do {
        let result = try await api.sendCommandToVehicle(vehicle!, command: VehicleCommand.startAutoConditioning)
       // success, also check result
} catch  {
    // no success
}
    }
}
