### ISSUE TITLE
Siri API call

### ISSUE THREAD

**Issue by sj10lon** [jonasman/TeslaSwift#122]
Is it possible to add Siri shortcuts? I know I can make Siri shortcuts to open the app and do a function inside the app, but is it possible to make a API call using Siri, without having to open up the app? For example: "Hey Siri, open doors", and then the doors get's opened up?

**Comment by jonasman** [comment]
Yes you can do such things with the current library.

**Comment by sj10lon** [comment]
> Yes you can do such things with the current library.

May I ask how to proceed to do this?
