### ISSUE TITLE
Add a custom command

### ISSUE THREAD

**Issue by Urkman** [jonasman/TeslaSwift#128]
What do you think about adding a custom command?
So we could use/test new endpoints like then door unlatch:
https://github.com/timdorr/tesla-api/issues/637

**Comment by jonasman** [comment]
I think it is easier to just add the new command?

**Comment by core-hacked** [comment]
@Urkman it's easier to just whip up a quick python script, send it out with curl or use postman.
No need to add this into the library. Most will not use this anyways, it's just pointless code from a development standpoint.
