### ISSUE TITLE
Options for Asset Image of car

### ISSUE THREAD

**Issue by Urkman** [jonasman/TeslaSwift#129]
Hello,

is there a way to get the options needed to create an image of the car?

Here is the url:
https://static-assets.tesla.com/v1/compositor/?model=my&view=STUD_3QTR&size=1440&options=$APF2,$APBS,$DV4W,$INPB0,$PPMR,$PRMY1,$SC04,$MDLY,$WY20P,$MTY09,$STY5S,$CPF1&bkba_opt=1&crop=1450,600,250,300

And I'm talking about the part "options=$APF2,$APBS,$DV4W,$INPB0,$PPMR,$PRMY1,$SC04,$MDLY,$WY20P,$MTY09,$STY5S,$CPF1"

**Comment by jonasman** [comment]
it is in the vehicle object

**Comment by Urkman** [comment]
But for me this is always nil :(

**Comment by Urkman** [comment]
What could be the reason, that option_codes is always null?
Even when I use a REST Client?

**Comment by jonasman** [comment]
it used to be on `option_codes` inside the vehicle obj, but it seems that Tesla removed this
