### ISSUE TITLE
swift 4

### ISSUE THREAD

**Issue by jonasman** [jonasman/TeslaSwift#13]
Swift 4 related issue

- [x] Convert Code

- [x] Remove ObjectMapper

**Comment by drewpitchford** [comment]
I'd appreciate it if you removed promisekit too.  Just use closure on the TeslaSwift methods: a success closure and a failure closure.

**Comment by jonasman** [comment]
Im not planning on removing PK for now.

Sent from my iPhone

On 30 Jun 2017, at 04:17, Drew Pitchford <notifications@github.com<mailto:notifications@github.com>> wrote:


I'd appreciate it if you removed promisekit too. Just use closure on the TeslaSwift methods: a success closure and a failure closure.

**Comment by perteadrian** [comment]
Hi @jonasman , when would you estimate the swift 4 conversion to be done ? Thank you.

**Comment by jonasman** [comment]
Somewhere this month.

Sent from my iPhone

On 19 Sep 2017, at 13:20, perteadi <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @jonasman<https://github.com/jonasman> , when would you estimate the swift 4 conversion to be done ? Thank you.

**Comment by jonasman** [comment]
there is now a swift 4 compatible version in master.
but i cannot update the pod trunk because the object mapper is not compatible.

**Comment by flexgames** [comment]
It's working for me - I bypassed this by simply compiling ObjectMapper independently and then including in the project (and removing it from the pod).

**Comment by drewpitchford** [comment]
There is a Swift 4 branch of ObjectMapper now. 

Drew

**Comment by jonasman** [comment]
Removing ObjectMapper and convert to Codable is a very painful task. 
Im reconsidering if i will do it or not. 
There is a branch already most of the conversion done. 
But the lack of support from Codable to convert basic stuff is a bit demotivating.

**Comment by jonasman** [comment]
Today i finished the conversion to `Codable`
Took some time but it was a good learning :)

Will merge soon

**Comment by flexgames** [comment]
Fantastic work

Joe

**Comment by jonasman** [comment]
4.0.0 is out
