### ISSUE TITLE
App Store Review

### ISSUE THREAD

**Issue by Urkman** [jonasman/TeslaSwift#130]
One more question...
I wanted to push a version to TestFlight, but it was not approved.
They want me to add a credentials for a Demo Account.
How did you handle this?

**Comment by jonasman** [comment]
I added support for a demo account that just fakes all the resposes

**Comment by Urkman** [comment]
I also thought about that. But how did you handle the login?
Did you create a dummy account at Tesla?
And if so, how did you get, that the current login is you demo account?
api.email is always null for me...

Perhaps you have some more hints to share?

**Comment by Urkman** [comment]
OK, found a way...
Added the "users/me" endpoint to library, with that I can get the authenticated user :)
With this data I get fake the responses, when needed...

**Comment by akac** [comment]
> I added support for a demo account that just fakes all the resposes

Sorry - I'm sure it's obvious and I'm just being obtuse…but can you explain a little bit on how you added support? Is this something you did within the library, or something you did by intercepting/mocking the network connection? Or was it by having a "demo mode" in the app that just hard faked the data.
