### ISSUE TITLE
ShareToVehicleOptions: Add option to send GPS coordinates as destination

### ISSUE THREAD

**Issue by Krillle** [jonasman/TeslaSwift#132]
Some places on earth don't have regulate street address, especially charging stations along highway. So it would be great to share to vehicle geo coordinates (GPS) as a destination. 

As far as I unterstand the `ShareToVehicleOptions`, this is not possible now, or is it?

While most applications apparently send a postal address to the car, the Google Maps application is sending precise geo coordinates. So the Tesla API seems to accept them.

**Comment by Krillle** [comment]
This gives a hint how to do it, unfortunately nor further explained: 

API:
[https://owner-api.teslamotors.com/api/1/vehicles/{remote_id}/command/share](https://owner-api.teslamotors.com/api/1/vehicles/%7Bremote_id%7D/command/share)

> Post JSON:
```

{
  "type": "share_ext_content_raw",
  "value": {
    "android.intent.extra.TEXT": "{There is no subject, only lng and lat}"
  },
  "locale": "zh-CN"
}

```
> Just put the latlon value and that's it. No prefix or tag is needed.

See https://github.com/timdorr/tesla-api/issues/188#issuecomment-624065809

**Comment by jonasman** [comment]
Did you figure out the data needed?

**Comment by jonasman** [comment]
@Krillle this seems easy to implement
is "{There is no subject, only lng and lat}" just `"1.2,3.4"` ?

**Comment by jonasman** [comment]
so i added this to the master branch, give it a try as im not able to right now. If it is buggy we can fix it

**Comment by Krillle** [comment]
@jonasman thanks for catching up with my idea. I implemented sending coordinate with TeslaSwift version 11.1.2. 
Unfortunately beta testers report, it was not working. I will be back at my own car on Thursday and can test it myself by then.

While no error is thrown, car is not receiving any destination, the testers said:

```
static func sendCoordinate (coordinate: CLLocationCoordinate2D) {
  if let vehicle = Tesla.car.vehicle {
      let shareToVehicleOptions = ShareToVehicleOptions(coordinate: coordinate)
      Task {
          do {
              let _ = try await Tesla.api.sendCommandToVehicle(vehicle, command: VehicleCommand.shareToVehicle(options: shareToVehicleOptions))
              print("TESLA API: Coordinate sent", coordinate)
          } catch let error {
              print("TESLA API: Sending coordinate failed:", error)
          }
      }
  }
}
```

**Comment by Krillle** [comment]
@jonasman thanks for catching up with my idea. I implemented sending coordinate with TeslaSwift version 11.1.2. 
Beta testers report, it is nicely working. I will be back at my own car on Thursday and can test it myself by then.

```
static func sendCoordinate (coordinate: CLLocationCoordinate2D) {
  if let vehicle = Tesla.car.vehicle {
      let shareToVehicleOptions = ShareToVehicleOptions(coordinate: coordinate)
      Task {
          do {
              let _ = try await Tesla.api.sendCommandToVehicle(vehicle, command: VehicleCommand.shareToVehicle(options: shareToVehicleOptions))
              print("TESLA API: Coordinate sent", coordinate)
          } catch let error {
              print("TESLA API: Sending coordinate failed:", error)
          }
      }
  }
}
```

Log Output: 
`TESLA API: Coordinate sent CLLocationCoordinate2D(latitude: 51.888644, longitude: 13.836824)`

**Comment by Krillle** [comment]
I can confirm testing on my own car: It's working nicely.

**Comment by jonasman** [comment]
@Krillle i would like to test
