### ISSUE TITLE
Tesla login broken

### ISSUE THREAD

**Issue by Jim3750** [jonasman/TeslaSwift#135]
The login to Tesla does not work any longer.

I saw in the bug files of the latest release of "Watch app for Tesla" the following:
- Fixed logion, which was broken due to an infrastructure change at Tesla

I made several trials with my app "Pilot Log for Tesla" (using TeslaSwift) and got 2 different behaviors, :
(1) the Tesla login screen is displayed, email and password can be entered, but result is "we don't recognize this sign in combination"
(2) the Tesla login goes thru but api.Authenticateweb fails with following error: "networkError(error: Error Domain=TeslaError Code=400 "(null)" UserInfo={ErrorInfo=Tesla1.ErrorMessage})"

Thank you for your help.

**Comment by jonasman** [comment]
https://github.com/timdorr/tesla-api/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
We need to check what the folks at the original api docs found out

**Comment by jonasman** [comment]
ok the fix is described here: https://github.com/timdorr/tesla-api/discussions/689#discussioncomment-5003678

**Comment by jonasman** [comment]
got it working on master

**Comment by Jim3750** [comment]
Awesome! « Pilot Log for Tesla » is on AppStore with login working again. Many thanks for your help.
