### ISSUE TITLE
Unauthorized oAuth uri

### ISSUE THREAD

**Issue by RSickenberg** [jonasman/TeslaSwift#137]
Hello,

When I tried to login with my app in prod, there was an issue with the url. ![image](https://user-images.githubusercontent.com/16922548/221393466-b9aa0a5c-4547-48cb-9688-fe0b9a62454c.png)

I'm not certain yet if the issue is from this lib or from Tesla. 

Best regards

**Comment by RSickenberg** [comment]
Also this:

![image](https://user-images.githubusercontent.com/16922548/221481578-0d632dc4-2efb-42e2-99c4-a041b80e3042.png)

**Comment by RSickenberg** [comment]
Oh I see this has been fixed on this commit:  https://github.com/jonasman/TeslaSwift/commit/f3da37fb7721ba05924b9a956f155219ab1bd274

Unfortunately, I'm trying to keep users on iOS 13 and Later, can this be backported to the 7.3.x branch?

**Comment by jonasman** [comment]
unfortunately Im not supporting iOS versions under 13, but i guess it would be easy to fork that branch and add that commit?

**Comment by RSickenberg** [comment]
@jonasman Which I did :)
