### ISSUE TITLE
Tesla.api.getVehicleChargeState() → TeslaError Code=404

### ISSUE THREAD

**Issue by Krillle** [jonasman/TeslaSwift#138]
`try await Tesla.api.getVehicleChargeState(vehicle)`

throws

`networkError(error: Error Domain=TeslaError Code=404 "(null)")`

Same code was working some days ago. Looks like Tesla changed something in API.

**Comment by jonasman** [comment]
It seems that some endpoints were removed: https://github.com/timdorr/tesla-api/issues/711

**Comment by jonasman** [comment]
you need to use now `getAllData`

**Comment by jonasman** [comment]
removed the deprecated apis now
