### ISSUE TITLE
3rd party permission?

### ISSUE THREAD

**Issue by sonpeter88** [jonasman/TeslaSwift#145]
Probably not the best place to ask but I wasn't sure where else. 

Has anyone run into an issue publishing an app on the ios App store using this library? I submitted my app for review but the reviewer asked me to upload proof that I got permission from Tesla to make an app controlling their cars. 

I noticed there are tons of apps on the store doing so. Did they all get permission to do so? Anyone know where to contact them?

**Comment by jonasman** [comment]
Never got asked such a thing. But heard from other apps something similar.

Sent from my iPhone

On 12 Aug 2023, at 00:29, Peter Son ***@***.***> wrote:

﻿

Probably not the best place to ask but I wasn't sure where else.

Has anyone run into an issue publishing an app on the ios App store using this library? I submitted my app for review but the reviewer asked me to upload proof that I got permission from Tesla to make an app controlling their cars.

I noticed there are tons of apps on the store doing so. Did they all get permission to do so? Anyone know where to contact them?

**Comment by sonpeter88** [comment]
Do you know what they had to do :( ?

**Comment by jonasman** [comment]
Im not sure

**Comment by jonasman** [comment]
i guess with the new API this is not a problem anymore
