### ISSUE TITLE
xCode 15 beta 7

### ISSUE THREAD

**Issue by imyrvold** [jonasman/TeslaSwift#147]
When I try to import TeslaSwiftStreaming in my project with xCode 15, I get an error in `TeslaStreaming` function `openStream` that says **Switch must be exhaustive**

**Comment by jonasman** [comment]
Hi, do you want to make a PR to fix it?

**Comment by imyrvold** [comment]
OK, I can do it 😄

**Comment by imyrvold** [comment]
The PR "Missing event case in TeslaStreaming" is awaiting your approval, this solves the error I had.

**Comment by wh1teSp** [comment]
same problem, can you fix please

**Comment by imyrvold** [comment]
The PR I made fixes the problem

**Comment by jonasman** [comment]
can you check now? i fixed a few things in master
