### ISSUE TITLE
Current Nav Destination Information

### ISSUE THREAD

**Issue by akac** [jonasman/TeslaSwift#152]
It would be nice to be able to get the current nav destination information as present in the main app. For example, I would like to pull that information out to support syncing what's in the main nav into Waze or Apple Maps.

**Comment by akac** [comment]
`active_route_destination": "Home",            "active_route_energy_at_arrival": 73,            "active_route_latitude": 39.533953,            "active_route_longitude": -104.741019,            "active_route_miles_to_arrival": 2.603559,            "active_route_minutes_to_arrival": 6.360438,            "active_route_traffic_minutes_delay": 0.0,`

**Comment by jonasman** [comment]
Can you make a PR?

**Comment by akac** [comment]
Yes I plan to. --Alex Kac, Father/HusbandOn Oct 29, 2023, at 3:34 PM, João Nunes ***@***.***> wrote:﻿
Can you make a PR?

**Comment by jonasman** [comment]
Hi, this was added in Tag 10.0.0, you need to pass the locationData endpoint when getting all data.

**Comment by jonasman** [comment]
Added this in Tag 10.1.0
