### ISSUE TITLE
Owner API will stop working as vehicles begin requiring end-to-end command authentication in 2024

### ISSUE THREAD

**Issue by itsMeDavidV** [jonasman/TeslaSwift#154]
Haven't used TeslaSwift, but have always appreciated what you have built here through the years, so hear's a heads up:

direct quote:

> Following the release of [Tesla Vehicle Command SDK](https://developer.tesla.com/docs/fleet-api#2023-10-02-tesla-vehicle-command-sdk) support for [REST API vehicle command endpoints](https://developer.tesla.com/docs/fleet-api#vehicle-commands) is now reaching end of life. Starting 2024 most vehicles will require sending commands via Tesla Vehicle Command SDK.
> 
> The use of [Tesla http proxy](https://github.com/teslamotors/vehicle-command/tree/main#using-the-http-proxy) is recommended for ease of development and to accelerate the transition to Tesla Vehicle Command (via SDK). When applicable, the proxy will transform Rest API HTTP commands into signed commands. Once configured, developers can simply point their application to the proxy without making any code changes to their application.

src: https://developer.tesla.com/docs/fleet-api?shell#fleet-telemetry

relevant repo: https://github.com/teslamotors/vehicle-command

**Comment by jonasman** [comment]
Thanks for the heads up!

I will have a look if we can create a swift version.
So far i only see official golang versions.

Sent from my iPhone

On 11 Oct 2023, at 09:43, David Villegas ***@***.***> wrote:

﻿

Haven't used TeslaSwift, but have always appreciated what you have built here through the years, so hear's a heads up:

direct quote:

Following the release of Tesla Vehicle Command SDK<https://developer.tesla.com/docs/fleet-api#2023-10-02-tesla-vehicle-command-sdk> support for REST API vehicle command endpoints<https://developer.tesla.com/docs/fleet-api#vehicle-commands> is now reaching end of life. Starting 2024 most vehicles will require sending commands via Tesla Vehicle Command SDK.

The use of Tesla http proxy<https://github.com/teslamotors/vehicle-command/tree/main#using-the-http-proxy> is recommended for ease of development and to accelerate the transition to Tesla Vehicle Command (via SDK). When applicable, the proxy will transform Rest API HTTP commands into signed commands. Once configured, developers can simply point their application to the proxy without making any code changes to their application.

src: https://developer.tesla.com/docs/fleet-api?shell#fleet-telemetry

relevant repo: https://github.com/teslamotors/vehicle-command

**Comment by itsMeDavidV** [comment]
cool! looking forward to seeing what you decide to do!

**Comment by jonasman** [comment]
Fleet API is now supported on master, i havent yet made the tag as some new APIs are missing and some more testing is also needed

**Comment by jonasman** [comment]
version 9 now includes Fleet API
