### ISSUE TITLE
Invalid code verifier

### ISSUE THREAD

**Issue by pinloop** [jonasman/TeslaSwift#162]
After a few months I have started to edit my project, and when I try to login using the example project code, I get the following message:

```
RESPONSE BODY ERROR: {"error":"invalid_request","error_description":"Invalid code verifier","error_uri":"https://auth.tesla.com/error/reference/97dbfe7c-2de7-41f5-a5d2-284d55ffb4c3-1704581253825"} 

Authentication failed: networkError(error: Error Domain=TeslaError Code=400 "(null)" UserInfo={ErrorInfo=TeslaSwift.ErrorMessage})
```

The is the code I am using:

```
let (webloginViewController, result) = api.authenticateWeb()

    guard let webloginViewController else { return }

    self.present(webloginViewController, animated: true, completion: nil)

    Task { @MainActor in
        do {
            _ = try await result()
            print("Authentication success")
            NotificationCenter.default.post(name: Notification.Name.loginDone, object: nil)

            self.dismiss(animated: true, completion: nil)
    } catch let error {
        print("Authentication failed: \(error)")
    }
}
```

How can I get my login to work without using the new Tesla Official API?

**Comment by jonasman** [comment]
I think the old api was killed on the new year

Sent from my iPhone

On 7 Jan 2024, at 00:53, pinloop ***@***.***> wrote:

﻿

After a few months I have started to edit my project, and when I try to login using the example project code, I get the following message:

RESPONSE BODY ERROR: {"error":"invalid_request","error_description":"Invalid code verifier","error_uri":"https://auth.tesla.com/error/reference/97dbfe7c-2de7-41f5-a5d2-284d55ffb4c3-1704581253825"}

Authentication failed: networkError(error: Error Domain=TeslaError Code=400 "(null)" UserInfo={ErrorInfo=TeslaSwift.ErrorMessage})


The is the code I am using:

let (webloginViewController, result) = api.authenticateWeb()

    guard let webloginViewController else { return }

    self.present(webloginViewController, animated: true, completion: nil)

    Task { @MainActor in
        do {
            _ = try await result()
            print("Authentication success")
            NotificationCenter.default.post(name: Notification.Name.loginDone, object: nil)

            self.dismiss(animated: true, completion: nil)
    } catch let error {
        print("Authentication failed: \(error)")
    }
}


How can I get my login to work without using the new Tesla Official API?

**Comment by pinloop** [comment]
@jonasman Oh damn, so I guess I'll have to move over the the new one then..
