### ISSUE TITLE
Tesla old owner API no longer supported? "getVehicles" gives error 412 since Jan 23rd 

### ISSUE THREAD

**Issue by Jim3750** [jonasman/TeslaSwift#164]
I still use the old API. Since yesterday the getVehicles command gives error 412. The login itself works fine.

Does it mean using Fleet API is now mandatory?

Thks

**Comment by jonasman** [comment]
most likely

**Comment by Krillle** [comment]
Using the new FleetAPI, I am getting a token with new FleetAPI, but still getVehicles command gets error 412. 

App is registered for scope Vehicle Information and Vehicle Commands.
@jonasman What else do I need to change to switch to new FeelAPI?? 

My code is matching the example in [TeslaSwiftDemo](https://github.com/jonasman/TeslaSwift/tree/master/TeslaSwiftDemo):

```      
static var api = TeslaSwift(teslaAPI: TeslaAPI.fleetAPI(region: .europeMiddleEastAfrica, clientID: clientID, clientSecret: clientSecret, redirectURI: redirectURI))

[...]

let (webloginViewController, result) = Tesla.api.authenticateWeb()   // ← This is successful. Tokes is issued and App listed as authorized in my Tesla account.

Task { @MainActor in
         _ = try await result()
        guard Tesla.api.isAuthenticated else { return }
        Task { @MainActor in
            do {
                let vehicles = try await Tesla.api.getVehicles()   // ← This fails with Error Domain=TeslaError Code=412
            } catch {
                #if DEBUG
                    print("Authentication: Requesting vehicles failed,", error)
                #endif
            }
        }
    }
}
```

**Comment by woTaniGitHub** [comment]
@Krillle Thanks for the quick response.

Please excuse the delay in responding due to the time difference.

I have read several documents, including the official documentation of the link.
I noticed that I have not done the indicated d...

I will implement them and POST the results here.
Thanks for the great support.

by Masahiko

**Comment by woTaniGitHub** [comment]
I will also try the following code from TeslaSwift. I believe this one is easier to register.

getPartnerToken(code: String)
registerApp(domain: String)

by Masahiko

**Comment by Krillle** [comment]
@woTaniGitHub  you just need to do these steps once. So for me doing it via curl or postman was more easy. 

Especially I didn’t figure out what parameter code is expected in `getPartnerToken(code: String)`.

**Comment by woTaniGitHub** [comment]
@Krillle We have successfully retrieved the getVehicles() data.
Thanks for your support.


RESPONSE: Optional(https://fleet-api.prd.na.vn.cloud.tesla.com/api/1/vehicles?)
STATUS CODE: 200
HEADERS: [
"Vary": "Accept"
"x-envoy-upstream-service-time": "166"
"Content-Type": "application/json; charset=utf-8"
"Date": "Wed, 14 Feb 2024 15:50:02 GMT"
.......


![スクリーンショット 2024-02-15 1 32 45](https://github.com/jonasman/TeslaSwift/assets/1286398/f5849e5a-f498-40b1-a1ca-61493a7ef34b)

In the end, I registered with the TeslaAPI curl.

**Comment by jonasman** [comment]
@Krillle are you using a car other than the old model S/X? then the library is not working

**Comment by Krillle** [comment]
@jonasman Yes, I am using Model S 2023, Model 3 2023 and 2022. And the library is working with all of them.

The issues have been my mistake. These steps have been missing:

C — Generate the partner authentication token
D — Register the app using a authentication token

**Comment by jonasman** [comment]
ok good, i have some issues with my users that they dont see the cars. Not sure why

**Comment by jonasman** [comment]
@Krillle i removed the code param as it was not necessary.

Since this is fixed i will close the issue
