### ISSUE TITLE
Instructions unclear for FleetAPI

### ISSUE THREAD

**Issue by corear** [jonasman/TeslaSwift#165]
I'm aware that the listed instructions are likely enough for most developers, but as a hobbyist, I'm unable to decipher what's needed to migrate from the OwnerAPI to the new FleetAPI. I've spent days trying to figure it out, but to no avail. @jonasman are you able to update the instructions or run through them in a one-on-one session to help me sort everything out? Please reach out at info@appbytes.net if so. I would be willing to compensate you for your time. Thanks.

**Comment by jonasman** [comment]
Hi,

Can you post some code and where do you get stuck?
Sent from my iPhone

On 29 Jan 2024, at 22:44, Collin ***@***.***> wrote:

﻿

I'm aware that the listed instructions are likely enough for most developers, but as a hobbyist, I'm unable to decipher what's needed to migrate from the OwnerAPI to the new FleetAPI. I've spent days trying to figure it out, but to no avail. @jonasman<https://github.com/jonasman> are you able to update the instructions or run through them in a one-on-one session to help me sort everything out? I would be willing to compensate you for your time. Thanks.

**Comment by Krillle** [comment]
@jonasman, I am stuck as well. I change my code to Fleet API. It was was working well with Owners API before.

The FleetAPI app registration is working fine. My app is getting approval for access to my Tesla Account. I can see my app in my Tesla account under **Third Party Apps** and it has access rights to **Vehicle Information** and **Vehicle Commands**

But I trying to get the list of my vehicles by `Tesla.api.getVehicles()`, I am getting `Error Domain=TeslaError Code=412`. I did not touch the code for getting the vehicles. Has the TeslaSwift API been changed here?

This is the relevant part of my code. It is a straight forward copy of the example in [TeslaSwiftDemo](https://github.com/jonasman/TeslaSwift/tree/master/TeslaSwiftDemo):

```static var api = TeslaSwift(teslaAPI: TeslaAPI.fleetAPI(region: .europeMiddleEastAfrica, clientID: clientID, clientSecret: clientSecret, redirectURI: redirectURI))

[...]

let (webloginViewController, result) = Tesla.api.authenticateWeb()   // ← This is successful. Tokes is issued and App listed as authorized in my Tesla account.

Task { @MainActor in
         _ = try await result()
        guard Tesla.api.isAuthenticated else { return }
        Task { @MainActor in
            do {
                let vehicles = try await Tesla.api.getVehicles()   // ← This fails with Error Domain=TeslaError Code=412
            } catch {
                #if DEBUG
                    print("Authentication: Requesting vehicles failed,", error)
                #endif
            }
        }
    }
}
```

I would be grateful for some advice, what I need to change.

**Comment by Krillle** [comment]
@corear  you need to setup the **redirectURI** in developer.tesla.com.

First you need to register your company or business. You can use a fake VAT number like DE12345678 if you don't have one, but sooner or later it might be verified.

Then you need to register your app. 
You will need a web server with your own domain, to place credentials on it. 
And there you enter your redirect URI, which needs to match the one, you call TeslaSwift .fleetAPI with. 

Find the detailed instructions [here](https://github.com/jonasman/TeslaSwift?tab=readme-ov-file#app-registration-for-the-fleet-api):

Follow the steps on the [official documentation](https://developer.tesla.com/docs/fleet-api#setup):

1. Create a private/public key and upload the public key to a website ([see here](https://docs.acquia.com/cloud-platform/manage/ssh/getting-started-ssh/generate/#))
2. Make a new app at [Tesla Developer](https://developer.tesla.com/dashboard)
3. Get a partner token (using this Library) (I did that manually in Tesla Developer)
4. Register your app (using this Library) (I did that manually in Tesla Developer)

**Comment by corear** [comment]
@Krillle Thank you for that detailed walkthrough! I have a site hosted on GoDaddy, and Firebase for my project. Am I able to store the public key in either one of those? What's tripping me up is the bit about the `/.well-known` section

**Comment by Krillle** [comment]
@corear Here at [Medium](https://shankar-k.medium.com/tesla-developer-api-guide-account-setup-app-creation-registration-and-third-party-da24aba1bddd) is a very good and detailed guide how to do it.

**Comment by corear** [comment]
@Krillle That had everything I needed, and my app is working again! Thank you very much!

The only issue I'm having now is that none of the commands are working. Each one returns the error `unsigned_cmds_hardlocked`. Here is an example of one command:
`Task {
                                    do {
                                        let data = try await api.sendCommandToVehicle(Vehicle.vehicleObject, command: .chargeLimitPercentage(limit: Int(maxCharge)))
                                        print("\(data.result): \(data.reason)")
                                        Vehicle.chargeState!.chargeLimitSOC = Int(maxCharge)
                                    }
                                    catch let error {
                                        print(error)
                                    }
                                }`

**Comment by Krillle** [comment]
@corear  did you register your app for Vehicle Command API?
<img width="1156" alt="Bildschirmfoto 2024-02-15 um 16 00 07" src="https://github.com/jonasman/TeslaSwift/assets/2863110/9796f023-a083-4dce-9bc5-73767f523d62">

**Comment by corear** [comment]
Yes, this is my scope:
<img width="815" alt="image" src="https://github.com/jonasman/TeslaSwift/assets/15691029/dd15b50d-8e7a-4fed-adea-c7a75a6365df">

**Comment by corear** [comment]
From a quick [Google search](https://shankarkumarasamy.blog/2023/10/29/tesla-developer-api-guide-account-setup-app-creation-registration-and-third-party-authentication-configuration-part-1/), it looks like I need to pass in that key I generated with the request, but I don't think TeslaSwift allows me to the way it's set up? @Krillle @jonasman

**Comment by Krillle** [comment]
After switching to FleetAPI, my code works without any changes, as well sending commands. So I assume the problem is on your Tesla-side. The generated private key is not needed, surprisingly. Only the public key needs to be publish in .well-known.

In case my implementation might give you hints, this is all I am doing to send commands to a vehicle after successful authentication 

```
var api = TeslaSwift(teslaAPI: TeslaAPI.fleetAPI(region: .europeMiddleEastAfrica, clientID: clientID, clientSecret: clientSecret, redirectURI: redirectURI))

api.reuse(token: token)

let shareToVehicleOptions = ShareToVehicleOptions(address: address)
try await Tesla.api.sendCommandToVehicle(vehicle, command: VehicleCommand.shareToVehicle(options: shareToVehicleOptions))

try await Tesla.api.wakeUp(vehicles[vehicle.id])
```

**Comment by Krillle** [comment]
@corear After switching to FleetAPI, my code works without any changes, as well sending commands. So I assume the problem is on your Tesla-side. The generated private key is not needed, surprisingly. Only the public key needs to be publish in .well-known.

In case my implementation might give you hints, this is all I am doing to send commands to a vehicle after successful authentication:

```
var api = TeslaSwift(teslaAPI: TeslaAPI.fleetAPI(region: .europeMiddleEastAfrica, clientID: clientID, clientSecret: clientSecret, redirectURI: redirectURI))

api.reuse(token: token)

let shareToVehicleOptions = ShareToVehicleOptions(address: address)
try await Tesla.api.sendCommandToVehicle(vehicle, command: VehicleCommand.shareToVehicle(options: shareToVehicleOptions))

try await Tesla.api.wakeUp(vehicles[vehicle.id])
```

**Comment by corear** [comment]
@Krillle Bizarre. I've doubled-checked my public key is still in .well-known/appspecific on my site and my code should work. Thank you for your help thus far, I'll keep working on finding a solution.

**Comment by corear** [comment]
Funny enough, the only ones I've found that still work are shareToVehicle and stopAutoConditioning. Not even startAutoConditioning works which is funny.

**Comment by wh1teSp** [comment]
> Funny enough, the only ones I've found that still work are shareToVehicle and stopAutoConditioning. Not even startAutoConditioning works which is funny.

Same
