### ISSUE TITLE
Calling the jsonObject method of a Vehicle causes a crash

### ISSUE THREAD

**Issue by omarqazi** [jonasman/TeslaSwift#20]
Xcode log output pasted below. 

2018-07-09 19:48:25.744729-0700 StoreWheels[35683:2885074] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSJSONSerialization dataWithJSONObject:options:error:]: Invalid top-level type in JSON write'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010eb101e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x000000010cb0a031 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010eb85975 +[NSException raise:format:] + 197
	3   Foundation                          0x000000010c5140a5 +[NSJSONSerialization dataWithJSONObject:options:error:] + 253
	4   TeslaSwift                          0x000000010c3ba9a9 _T0s9EncodableP10TeslaSwiftE10jsonObjectypSgvg + 297
	5   StoreWheels                         0x000000010bdfd67f _T011StoreWheels19TeslaViewControllerC14updateVehiclesyyFyycfU_ + 399
	6   StoreWheels                         0x000000010bdfda21 _T011StoreWheels19TeslaViewControllerC14updateVehiclesyyFyycfU_TA + 17
	7   StoreWheels                         0x000000010bdfda5d _T0Ieg_IeyB_TR + 45
	8   libdispatch.dylib                   0x0000000111e287ab _dispatch_call_block_and_release + 12
	9   libdispatch.dylib                   0x0000000111e297ec _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x0000000111e2e619 _dispatch_queue_override_invoke + 1451
	11  libdispatch.dylib                   0x0000000111e3536c _dispatch_root_queue_drain + 664
	12  libdispatch.dylib                   0x0000000111e35076 _dispatch_worker_thread3 + 132
	13  libsystem_pthread.dylib             0x0000000112354169 _pthread_wqthread + 1387
	14  libsystem_pthread.dylib             0x0000000112353be9 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by jonasman** [comment]
I will remove that method in the next versions

**Comment by jonasman** [comment]
4.4.0 removed this method
