### ISSUE TITLE
Failed authentication

### ISSUE THREAD

**Issue by mflottDesign** [jonasman/TeslaSwift#21]
While trying to get authenticated it fails with the error: 

`Error Domain=TeslaSwift.TeslaError Code=1 "(null)"`

This is probably not due to the the API, but the servers. Anyways, this issue has been discussed on TMC [(Error in Tesla API)](https://teslamotorsclub.com/tmc/threads/error-in-tesla-api.127239/), and by using the additional headers:

`User-Agent: Mozilla/5.0 (Linux; Android 9.0.0; VS985 4G Build/LRX21Y; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/58.0.3029.83 Mobile Safari/537.36`

`X-Tesla-User-Agent: TeslaApp/3.4.4-350/fad4a582e/android/9.0.0`

it seems to work properly, at least on tesla-api page on apiary.

**Comment by mflottDesign** [comment]
Did you find time to look at it? The issue is still present.

**Comment by jonasman** [comment]
Will fix it this week

Sent from my iPhone

On 9 Sep 2018, at 19.50, Marius Flottorp <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you find time to look at it? The issue is still present.

**Comment by jonasman** [comment]
I tried to authenticate and i dont see this issue

**Comment by mflottDesign** [comment]
That's strange. Just checked again in xCode, on a build of the app on my phone and on apiary and it's still the same for me. On Apiary I get the response _"Our servers are waiting for a supercharger spot.."_. If I add the additional headers I mentioned I get the correct response on apiary. It worked perfectly fine a couple of days before I submitted this issue.

What about adding a method for just adding additional headers to the request?

**Comment by jonasman** [comment]
I can add the headers to the lib but it is odd that i dont get this issue. What is your car and version?

Mine is a Model S, old MCU, 2018.32.4

**Comment by mflottDesign** [comment]
Same car and version.

In xCode I get don't even get to try any commands since it won't authorize in any way.
I get the same response on all commands on apiary, using the latest token I had before the issue. Same response when trying to authorize too.

It's really odd, indeed. Doesn't look like the X-Tesla-User-Agent header is needed though, I get the proper response with only the User-Agent.

**Comment by jonasman** [comment]
can you try if `User-Agent: TeslaSwift` header works?

**Comment by mflottDesign** [comment]
Yeah, it works. It was actually mentioned in the forum link I posted before that the User-Agent only needed an arbitrary value for some reason.

**Comment by mflottDesign** [comment]
Thanks a lot. Now everything works again.
