### ISSUE TITLE
Streaming API only returning nil events

### ISSUE THREAD

**Issue by EpicDraws** [jonasman/TeslaSwift#23]
Been trying to figure what is going on across several vehicles (Model X and Model 3) and it seems that the stream fails to open but all errors are nil and no information seems to be given. I'm passing in the Vehicle object I get from a getVehicles() call. Are others facing this?

**Comment by jonasman** [comment]
It is working ok for me.

**Comment by jonasman** [comment]
maybe it is due to the user agent missing.

**Comment by EpicDraws** [comment]
Thanks. Are you adding in a user agent manually?

**Comment by jonasman** [comment]
my car does not need a user agent. Can you add it and let me know if that fixes the issue?

**Comment by jakeholland** [comment]
Doesn’t work on my model 3, but I think that is a model 3 issue. I have been experimenting with the other websocket streaming api that apparently has been working for others. I have a branch with some changes. I might be able to look at it tonight.

**Comment by jonasman** [comment]
yeah. model 3 is known to not work.

**Comment by EpicDraws** [comment]
Thanks @jakeholland 

I was also trying with 2 different Model X and got the same errors. I'd love to see what you're working on, and ultimately would love a solution that works with Model 3 too.

**Comment by jonasman** [comment]
@EpicDraws i tried to add user agent to the streaming but it breaks the stream and sends nils all the time.

**Comment by jonasman** [comment]
@EpicDraws were you able to stream?

**Comment by mortimern** [comment]
I have a model S 2017 2019.4.3 and it is not streaming. I get this response:

Opening Stream to: https://streaming.vn.teslamotors.com/stream/xxxxxxxxx/?values=speed,odometer,soc,elevation,est_heading,est_lat,est_lng,power,shift_state,range,est_range,heading
Stream open
Stream data: <html>
Stream data: <head><title>502 Bad Gateway</title></head>
Stream data: <body bgcolor="white">
Stream data: <center><h1>502 Bad Gateway</h1></center>
Stream data: <hr><center>nginx</center>
Stream data: </body>
Stream data: </html>
Stream error: nil
nil Event
Stream closed

Any progress on this error? I have tried to find answers, but seems the endpoint has changed? The original Tesla App works fine..

**Comment by jonasman** [comment]
@mortimern MCU v2?

**Comment by mortimern** [comment]
AP2, MCU1 i believe.. is there a difference between the two?

**Comment by jonasman** [comment]
I get the same error now:
```
Opening Stream to: https://streaming.vn.teslamotors.com/stream/XX/?values=speed,odometer,soc,elevation,est_heading,est_lat,est_lng,power,shift_state,range,est_range,heading
Stream open
Stream data: <html>
Stream data: <head><title>502 Bad Gateway</title></head>
Stream data: <body bgcolor="white">
Stream data: <center><h1>502 Bad Gateway</h1></center>
Stream data: <hr><center>nginx</center>
Stream data: </body>
Stream data: </html>
Stream error: nil```

**Comment by jonasman** [comment]
following https://github.com/timdorr/tesla-api/issues/97 to see if they figure it out

**Comment by jonasman** [comment]
@mortimern are you sure you dont get some streaming events? In my car i get around 8 events before 502 kicks in

**Comment by mortimern** [comment]
@jonasman I have not checked for a while now as I made a dirty way around it, but will check again soon. I will try to make it happen within a couple of days :) but with 8 events it is still a little sketchy..

**Comment by jonasman** [comment]
@mortimern i checked and those events were just bugs. I confirm streaming for me is also gone

**Comment by jonasman** [comment]
It seems that Tesla has changed from HTTPEventStream to a websocket under `wss://streaming.vn.teslamotors.com/streaming/`

As soon as i have some more time I will implement a WEBSocket stream

Here's where I found the details: `https://github.com/timdorr/tesla-api/blob/master/lib/tesla_api/stream.rb`

**Comment by mortimern** [comment]
I can look at it too and see if I can help in any way :)

Mvh Morten Fjeldberg

20. okt. 2019 kl. 13:01 skrev João Nunes <notifications@github.com>:

﻿

It seems that Tesla has changed from HTTPEventStream to a websocket under wss://streaming.vn.teslamotors.com/streaming/

As soon as i have some more time I will implement a WEBSocket stream

Here's where I found the details: https://github.com/timdorr/tesla-api/blob/master/lib/tesla_api/stream.rb

**Comment by jonasman** [comment]
Don’t worry, I already have the code working. I can get stream events but still figuring some things out.

João

Sent from my iPhone

On 20. Oct 2019, at 15.51, mortimern <notifications@github.com> wrote:

﻿I can look at it too and see if I can help in any way :)

Mvh Morten Fjeldberg

20. okt. 2019 kl. 13:01 skrev João Nunes <notifications@github.com>:

﻿

It seems that Tesla has changed from HTTPEventStream to a websocket under wss://streaming.vn.teslamotors.com/streaming/

As soon as i have some more time I will implement a WEBSocket stream

Here's where I found the details: https://github.com/timdorr/tesla-api/blob/master/lib/tesla_api/stream.rb

**Comment by mortimern** [comment]
Ok, nice :)

Looking forward to having the real stream again instead of the dirty way og updating every 5seconds.. :)
Havent done much with the app for a while, but had to fix now for v10. Will be good with streaming too :)

Mvh Morten Fjeldberg

20. okt. 2019 kl. 14:57 skrev João Nunes <notifications@github.com>:

﻿Don’t worry, I already have the code working. I can get stream events but still figuring some things out.

João

Sent from my iPhone

On 20. Oct 2019, at 15.51, mortimern <notifications@github.com> wrote:

﻿I can look at it too and see if I can help in any way :)

Mvh Morten Fjeldberg

20. okt. 2019 kl. 13:01 skrev João Nunes <notifications@github.com>:

﻿

It seems that Tesla has changed from HTTPEventStream to a websocket under wss://streaming.vn.teslamotors.com/streaming/

As soon as i have some more time I will implement a WEBSocket stream

Here's where I found the details: https://github.com/timdorr/tesla-api/blob/master/lib/tesla_api/stream.rb

**Comment by jonasman** [comment]
Please have a look at the latest master / 6.3.0 tag if you need Streaming. It should work. 
from my limited tests, the stream is not very stable and closes too early

**Comment by mortimern** [comment]
Ok, will have a look, I see that a lot more has changed too. Can I still use promises and the other 4.8 structure with 6.3?

**Comment by jonasman** [comment]
@mortimern you can use swift callbacks, Promises, RX (new) or Combine (new) for the whole library.
For data streaming you can use callbacks (like it used to be before), RX (new) or Combine (new).

**Comment by mortimern** [comment]
Ok, will update and see what I get :)
Thanks for the really quick answer :)

**Comment by mortimern** [comment]
Any special tricks to get 6.3.0? It will only fetch 6.2.0 on pod update. When I try to force 6.3.0 in pod file it does not find it. I do get 6.2.0 to start stream, but still the 502 bad gateway message, so I believe the 6.3.0 fixes that?

**Comment by jonasman** [comment]
i think the pod trunk update failed. you need to force the pod to get from master

**Comment by mortimern** [comment]
That worked, but still complains about the module Starscream. Tried to add to my podfile, but still not finding it. I see it is linked as a dependency in the TeslaSwift project, but do you have an idea of what's happening? I tried to clean and restart xcode, but no luck.

![Skjermbilde 2019-11-04 kl  16 05 05](https://user-images.githubusercontent.com/34065654/68131192-e523b300-ff1c-11e9-9000-10d175fc6ab4.png)

**Comment by jonasman** [comment]
you are right! i forgot to add that dependency on the podspec. 
If you want a working solution try with SPM

**Comment by jonasman** [comment]
podspec is updated. 6.3.1 should work fine

**Comment by mortimern** [comment]
Do you have some examplecode for the new stream? I do get the data, but how to read the TeslaStreamingEvent.event(StreamEvent)?

**Comment by mortimern** [comment]
Works good, just disconnects really often.. Anywhere from 5seconds to 2minutes between disconnects.

**Comment by jonasman** [comment]
I will close. We can reopen if after implementing #62 it still fails
