### ISSUE TITLE
Seat heater reporting issue in ClimateState

### ISSUE THREAD

**Issue by mortimern** [jonasman/TeslaSwift#36]
After implementing the new functionality I found that the ClimateState is not reporting back the status of the third row seat heaters. I have not access to a car with those seats, so can not add that to the climatestate functionality, but you might know someone with those seats activated? I did not find it in the API documentation either.

**Comment by mortimern** [comment]
Also the Climate State is reporting back Bool values for a few of the seats (not all) instead of the Int value 0-3. I have changed the ClimateState file and tested it in my fork, but might want to add the last seats before merge.

**Comment by jonasman** [comment]
Updated the values to Int. My car reports Int values atm.

**Comment by jonasman** [comment]
Closing as it seems to work as normal. I will reopen if you report issues again
