### ISSUE TITLE
Does TeslaSwift support HomeLink?

### ISSUE THREAD

**Issue by rawmean** [jonasman/TeslaSwift#46]
I'm specifically interested in HomeLink for Model 3.
I know a lot has changed wrt the API for HomeLink.

Thank you!

**Comment by jonasman** [comment]
Unfortunately not yet

Sent from my iPhone

On 19. Aug 2019, at 21.26, Ramin <notifications@github.com> wrote:

﻿

I'm specifically interested in HomeLink for Model 3.
I know a lot has changed wrt the API for HomeLink.

Thank you!

**Comment by mortimern** [comment]
Hi Jonasman,

I have added Homelink to the Homelink branch of my fork. I have not tested it yet, but will later today. I have also added window control in another branch. Feel free to add to main TeslaSwift library.

Morten

**Comment by jonasman** [comment]
Thanks! Can you PR?

Sent from my iPhone

On 15. Oct 2019, at 12.17, mortimern <notifications@github.com> wrote:

﻿

Hi Jonasman,

I have added Homelink to the Homelink branch of my fork. I have not tested it yet, but will later today. I have also added window control in another branch. Feel free to add to main TeslaSwift library.

Morten

**Comment by mortimern** [comment]
I did a PR, but some of the old steeringwheelheater stuff was also with in it.. I am not too familiar with Git, but im sure you can sort only the homelink out :)

**Comment by mortimern** [comment]
Homelink code is verified and working as intended. I could not test the window function as it is not supported by my car.. I do get the message back that it is not supported, so I assume it is working correctly.

**Comment by jonasman** [comment]
@rawmean now the library supports trigger homelink
