### ISSUE TITLE
V10 features

### ISSUE THREAD

**Issue by jonasman** [jonasman/TeslaSwift#48]
- [x] Max defrost
- [x] Windows control
- [x] Navigate Request --> Share

**Comment by mortimern** [comment]
You can find the Window control in my Fork. The pull request will probably not work from that either, but feel free to copy. I should probably delete that fork and make a new one..

**Comment by jonasman** [comment]
@mortimern thanks! i took some parts from your code. But the PR was in a bad state so i had to make a new one
