### ISSUE TITLE
Missing APIs

### ISSUE THREAD

**Issue by jonasman** [jonasman/TeslaSwift#49]
- [ ] service_data
- [x] VEHICLE_SUMMARY

**Comment by ericlewis** [comment]
@jonasman is service_data still missing?

**Comment by ericlewis** [comment]
I would be happy to take a look at it.

**Comment by jonasman** [comment]
I think it is. The prob is that testing is hard :)

**Comment by davidhodge** [comment]
What sort of data is in VEHICLE_SUMMARY?

**Comment by jonasman** [comment]
@davidhodge it is the normal vehicle object, without the extended data. It was just an API rename from tesla's side.

**Comment by davidhodge** [comment]
ah okay, thank you

**Comment by ericlewis** [comment]
@jonasman looked into the service API and it is dead simple, will do a PR later.

**Comment by jonasman** [comment]
@ericlewis cool :)
