### ISSUE TITLE
Unable to initialize TeslaSwift

### ISSUE THREAD

**Issue by nfrydenholm** [jonasman/TeslaSwift#5]
Hey

I was just curious about the Tesla api and came across your Swift Library.

However, I cannot use it in my own little "demo app", as the TeslaSwift class has no initializer.
So, since I'm not in the same module (as far as I understand it), it doesn't work.

When you don't define `init() {}` it's internal by default, so I get this whenever I try to do 
let api = TeslaSwift()
Error:(17, 19) 'TeslaSwift' initializer is inaccessible due to 'internal' protection level

**Comment by jonasman** [comment]
Sorry, a recent change broke the init. Fixed now
