### ISSUE TITLE
-sectalign and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together

### ISSUE THREAD

**Issue by ssneller** [jonasman/TeslaSwift#52]
First, love your pod. I've been playing with it for a couple of years now. On your latest version, it works great on the simulator, but when I try to run it on a real device (iphone 6 & X), I get an error 
ld: -sectalign and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jonasman** [comment]
I just compiled from master and it works fine. i dont see any reference to `sectalign`

**Comment by ericlewis** [comment]
@ssneller do you happen to be using a swift.org toolchain as opposed to the bundled one? Also, upgrading Xcode can help with this issue, try using the latest.

**Comment by jonasman** [comment]
I will close this for now. If you still have this issue please open again.
