### ISSUE TITLE
Split Streaming API into Extension?

### ISSUE THREAD

**Issue by Vortec4800** [jonasman/TeslaSwift#61]
Have you considered splitting off the Streaming API portion into its own extension? Might be nice so if an app doesn't need that portion, you wouldn't need to install the Starscream dependency and the entire library would be a bit smaller.

Just a thought.

**Comment by jonasman** [comment]
That thought has crossed my mind. I might do it

Sent from my iPhone

On 11 Oct 2020, at 04:02, Cory Imdieke <notifications@github.com> wrote:

﻿

Have you considered splitting off the Streaming API portion into its own extension? Might be nice so if an app doesn't need that portion, you wouldn't need to install the Starscream dependency and the entire library would be a bit smaller.

Just a thought.

**Comment by davidhodge** [comment]
If it helps at all, just wanted to add that I'd definitely appreciate this as well. +1

**Comment by jonasman** [comment]
I will probably do this as part of the #62

**Comment by jonasman** [comment]
Done on https://github.com/jonasman/TeslaSwift/pull/63
Merged to master and coming on version 7.0.0

Pods are uploading now but SPM should be ok
