### ISSUE TITLE
getVehicle with SwiftUI

### ISSUE THREAD

**Issue by filipmili** [jonasman/TeslaSwift#64]
Hi,

I'm a Beginner in Swift programming and I have a problem with getVehicles() in SwiftUI. I've called the function in a struct and want to get data in my View. For example: displayName, VIN , ... But It doesn't work, I only get a blank screen without any output. Can anyone help me?

**I have following in my struct:**
<img width="615" alt="Bildschirmfoto 2020-12-29 um 18 19 42" src="https://user-images.githubusercontent.com/35067161/103301951-c75bbc00-4a02-11eb-98dc-f819fd8779ac.png">

**And the function in my struct:**
<img width="376" alt="Bildschirmfoto 2020-12-29 um 18 20 40" src="https://user-images.githubusercontent.com/35067161/103302031-f5d99700-4a02-11eb-9286-b2604ebdbe2d.png">

**Output**
<img width="459" alt="Bildschirmfoto 2020-12-29 um 18 27 54" src="https://user-images.githubusercontent.com/35067161/103302288-9760e880-4a03-11eb-9b21-74428f413920.png">

Information: Im using the TeslaSwift framework with Pods & have imported following modules: Foundation, SwiftUI, TeslaSwift, PromiseKit
- Xcode: 12.3

**Comment by jonasman** [comment]
Did you call authenticate first?

Sent from my iPhone

On 29 Dec 2020, at 19:29, filipmili <notifications@github.com> wrote:

﻿

Hi,

I'm a Beginner in Swift programming and I have a problem with getVehicles() in SwiftUI. I've called the function in a struct and want to get data in my View. For example: displayName, VIN , ... But It doesn't work, I only get a blank screen without any output. Can anyone help me?

I have following in my struct:
[Bildschirmfoto 2020-12-29 um 18 19 42]<https://user-images.githubusercontent.com/35067161/103301951-c75bbc00-4a02-11eb-98dc-f819fd8779ac.png>

And the function in my struct:
[Bildschirmfoto 2020-12-29 um 18 20 40]<https://user-images.githubusercontent.com/35067161/103302031-f5d99700-4a02-11eb-9286-b2604ebdbe2d.png>

Output
[Bildschirmfoto 2020-12-29 um 18 27 54]<https://user-images.githubusercontent.com/35067161/103302288-9760e880-4a03-11eb-9b21-74428f413920.png>

Information: Im using the TeslaSwift framework with Pods & have imported following modules: Foundation, SwiftUI, TeslaSwift, PromiseKit

  *   Xcode: 12.3

**Comment by filipmili** [comment]
I called it in my other Login file to login into the app. The pictures I ve mentioned are after the login. 

Should I also take the authenticate func in my struct view?

**Comment by jonasman** [comment]
You need to keep the TeslaSwift() in a place where it does not get deallocated. When you do authentication you need to use the same object to do all the actions. You cannot authenticate in one and then create a new one.

**Comment by filipmili** [comment]
I've solved the problem. Thanks a lot.
