### ISSUE TITLE
AuthToken createdAt is nil

### ISSUE THREAD

**Issue by jaumecornado** [jonasman/TeslaSwift#67]
Made a PR to solve AuthToken.createdAt == nil

#66

**Comment by jonasman** [comment]
Tesla is not allowing anymore USER/PASS authentication. The new web authentication does not have `created_at` anymore. So im thinking to remove this filed in a next version

**Comment by jonasman** [comment]
https://github.com/jonasman/TeslaSwift/commit/eac81c062dd52f5026f5df0441b2331ce5da2114
