### ISSUE TITLE
api error handling

### ISSUE THREAD

**Issue by Jim3750** [jonasman/TeslaSwift#68]
I am successfully using the following code from the TeslaSwiftDemo to jet the full json string for a vehicle:

if let vehicle = vehicle {
			_ = api.getAllData(vehicle).done { (extendedVehicle: VehicleExtended) in
				self.textView.text = "All data:\n" +
				extendedVehicle.jsonString!
			}

Question is: which changes to write in such code to be able to handle the case in which the api is not able to get the jsonString?
I think I understood there is a time-out of 10s, but I would need to be able to trap the time-out event to handle properly such case.
Thank you for your help.

**Comment by jonasman** [comment]
Hi!

It seems that you using PromiseKit to get your data. check it out here: https://github.com/mxcl/PromiseKit/blob/master/Documentation/CommonPatterns.md

You need to use catch

**Comment by Jim3750** [comment]
Thank you for this answer pointing right to the solution! Besides, very easy to implement...
