### ISSUE TITLE
OSX Support 

### ISSUE THREAD

**Issue by HudsonGraeme** [jonasman/TeslaSwift#7]
Hello,

Thank you for the repo, but i cannot install the pod because my target is osx.
Unless it has compatibility issues, that would be a nice feature!

Thanks!

**Comment by jonasman** [comment]
Good idea. I will do it ASAP

**Comment by jonasman** [comment]
https://github.com/jonasman/TeslaSwift/commit/b7f07c33079aec1c288fa28179ce971e9ccc39af

**Comment by jonasman** [comment]
https://github.com/jonasman/TeslaSwift/tree/3.3.6

**Comment by HudsonGraeme** [comment]
Thank you very much!
