### ISSUE TITLE
Login not working after Tesla changed their APIs.

### ISSUE THREAD

**Issue by simengjermundsen** [jonasman/TeslaSwift#70]
Tesla changed the endpoint for login.
More info here: https://teslamotorsclub.com/tmc/threads/model-s-rest-api.13410/page-143
And here: https://github.com/timdorr/tesla-api/issues/260
And here: https://github.com/timdorr/tesla-api/discussions

**Comment by jonasman** [comment]
Hi, have you tried the new version 7? the library supports the new web authentication flow

**Comment by simengjermundsen** [comment]
No. I have not. I assumed this issue was more recent than it actually seems to be.
You are awesome!
