### ISSUE TITLE
Is there a way to get the personalized car photo?

### ISSUE THREAD

**Issue by Jim3750** [jonasman/TeslaSwift#71]
Maybe I missed it, but I did not see a way via the API to get the photo of a given car (like the one available on the Tesla web site when connected with personal credentials). Also did not manage to find any solution via Google, while some IOS apps are indeed displaying such photo.

Possible via the API? If not, any other input?

Thank you.

**Comment by jonasman** [comment]
That is not possible via the API.
You need to read the car specs and show the picture yourself.
