### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by Jim3750** [jonasman/TeslaSwift#74]
Most of the time API calls are proceeding OK, but sometimes I get repeatedly the following error "networkError(error: Error Domain=TeslaError Code=403" (for any type of call: login, getVehicles, wake-up, get data); then after retry-ing several times, it goes through.

Do you know what causes that and how to avoid it?

Thank you

**Comment by jonasman** [comment]
Hm didnt get that yet

**Comment by Jim3750** [comment]
I am still fighting with error 403 (access forbidden); not systematically, most of the time, everything works smoothly…
My code is the following, for instance for getVehicles:
———————————
var validToken = AuthToken (
        accessToken: "")
let api = TeslaSwift()
api.reuse(token: self.validToken)
api.getVehicles()
                .done { (result) in
			// code for success
               }.catch { (error) in
			// code for failure
			// this is where I  catch error 403
}
—————————————
At successful login, I store: 
- accessToken, tokenType, createdAt, expiresIn, refreshToken, idToken 
in validToken

Anything which could cause (not systematic) error 403?
Thank you.

**Comment by jonasman** [comment]
are you refreshing the token on time?
if you have a 5minutes token try to refresh before it expires

**Comment by Jim3750** [comment]
I made some trials adding token refresh with no effect.

I don’t think the issue is linked to token refresh:
- My understanding is that TeslaSwift takes care of refresh
- Indeed, the current code works (most of the time) even after several hours of no usage of the app (ie. the 5mn token having long expired)
- The 403 error can happen also within the 5mn…

I noticed the following:
- The 403 error appears very rarely on the iPhone simulator (not never however…)
- When I test the app, at the same time, on the simulator and on 2 iPhones (accessing the same car), I can get different behaviors (ex: all OK on the sim and one iPhone, and 403 error on the 2nd iPhone)

Looks like this « forbidden access » is linked (temporarily) to a given IP. Now, what could cause this is the question…

The msg I get from the system is: «networkError(error: Error Domain=TeslaError Code=403 "(null) ») »

**Comment by eliotwinchell** [comment]
I've seen the same error message randomly as well... According to Tim Dorr's API docs (https://tesla-api.timdorr.com/api-basics/authentication) "Tesla's SSO service has a WAF (web application firewall) that may temporarily block you if you make repeated, execessive requests... This normally presents as a "challenge" page, which requires running some non-trivial JavaScript code to validate that you have a full browser engine available." Maybe this is occurring? Although the response code shouldn't be a 403 right? I've never seen this challenge page on the official Tesla iOS app before however..

**Comment by Jim3750** [comment]
Update:
(1) I run the TeslaSwift demo app on an iPhone and was able to REPRODUCE the issue; ie. I got the following displayed on the login screen: "Authentication failed: networkError(error: Error Domain=TeslaError Code=403 "(null)" "; at the same time, on the iPhone simulator, the demo app runs fine...
(2) not 100% of time, but "often", when switching from Wifi to 4G (or reverse), this triggers the 403 error; ie. app works fine on Wifi; switch to 4G; next API call gives 403 error

**Comment by Jim3750** [comment]
Update:
I rechecked the refresh token matter, with the following findings:
- When api is called with a valid token, all OK (even switching 4G/Wifi)
- api call can be OK with an expired token (but in that case, not systematically OK)
- An expired token can be refreshed
- The refresh of a valid token can fail
- Refresh token request can get a 403 reply
- On simulator, 403 does not occur (to be more precise, occurs very rarely), even switching Wifi / 4G (via hotspot); it occurs only on iPhone (I tried several iPhones)

My conclusions for now:
- Since it happens (frequently on iPhone) to get 403 on refresh token request, it is not a full solution to the issue
- The fact to have no issue on simulator should demonstrate something, but I do not know what…

Code for refresh:
api.reuse(token: validToken)
 api.refreshWebToken { (result: Result<AuthToken, Error>) in
        DispatchQueue.main.async {
            do { 
			let token  = try result.get().accessToken
			// code to record the new token in « validToken » 
		} catch {
			// code to manage error 
		}
	}

**Comment by Jim3750** [comment]
Matter is resolved. 403 was caused by use of "api.reuse(validToken)" before each api call. I now use this just before "api.authenticateWeb".

**Comment by jonasman** [comment]
`api.reuse` should be used only once after you have a valid token, for example when you restart the app. 
If you will call authenticate then you do not need to reuse any token.

**Comment by Jim3750** [comment]
I forgot to mention that the issue with incorrect api.reuse was NOT happening on the iPhone simulator, but only on a physical device. Any clue why?

**Comment by SohrabYY** [comment]
I'm facing the same issue and for me didn't go away with `api.reuse(token)`. I also see this happening on physical device and not simulator.

**Comment by Jim3750** [comment]
Sorry for you, but glad to see I am not alone to face this... 
Issue is not fully resolved for me. This is where I stand: 
- when I have a successful api.authenticateWeb, I can run sucessfully all other api calls for 5mn (token valid); so before any api calls, I have to run api.authenticateWeb
- remaining issue is that, quite often, I get error 403 with api.authenticateWeb; and after a number (very variable) of retry, it ends up being successful
- this issue is ONLY on a physical device, never on the simulator; by the way, the same  (403 on authenticateWeb) happens with the demo app "TeslaSwift"

**Comment by jonasman** [comment]
Can you activate logs and see what the api is doing when it tried to refresh the token by itself?

**Comment by Jim3750** [comment]
Here is it for unsuccessful authenticateWeb (I replaced the id codes by ...).

2021-04-20 11:47:01.254939+0200 Tesla1[5320:1651717] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2021-04-20 11:47:01.255049+0200 Tesla1[5320:1651717] WF: _WebFilterIsActive returning: NO

REQUEST: https://auth.tesla.com/oauth2/v3/token?
METHOD: POST
REQUEST HEADERS: [
"Content-Type": "application/json"
"User-Agent": "TeslaSwift"
]
REQUEST BODY: {
  "client_id" : "ownerapi",
  "code" : « … »,
  "redirect_uri" : "https:\/\/auth.tesla.com\/void\/callback",
  "code_verifier" : « … »,
  "client_secret" : « … »,
  "grant_type" : "authorization_code"
}
2021-04-20 11:47:01.685261+0200 Tesla1[5320:1651717] [Process] 0x109012e18 - [pageProxyID=21, webPageID=22, PID=5324] WebPageProxy::didFailProvisionalLoadForFrame: frameID = 3, domain = WebKitErrorDomain, code = 102

RESPONSE: Optional(https://auth.tesla.com/oauth2/v3/token?)
STATUS CODE: 403
HEADERS: [
"Expires": "Tue, 20 Apr 2021 09:47:01 GMT"
"Date": "Tue, 20 Apr 2021 09:47:01 GMT"
"Content-Length": "291"
"Server": "AkamaiGHost"
"Content-Type": "text/html"
"mime-version": "1.0"
]
RESPONSE BODY ERROR: <HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
 
You don't have permission to access "http&#58;&#47;&#47;auth&#46;tesla&#46;com&#47;oauth2&#47;v3&#47;token&#63;" on this server.<P>
Reference&#32;&#35;18&#46;f721102&#46;1618912021&#46;16dd0ce2
</BODY>
</HTML>

**Comment by jonasman** [comment]
I just tried on simulator and it worked fine. 
1. WebLogin
2. wait 5 mins
3. Send Request -> 401
4. Send Request again, this time the lib asked for a refresh token. Got the token and 200 from the request

**Comment by jonasman** [comment]
on your logs i see that the POST header is missing the authorisation header and also the request body is incorrect, it should be a refresh token, not a new authentication. 

Are you forcing a token refresh or just letting the API to handle the refresh itself?

**Comment by Jim3750** [comment]
I am not forcing refresh. When the app starts, I just call authenticateWeb. No code "api.reuse".
After several 403 replies (loop with 1s interval), here is what I get in log for a successful authenticateWeb:

REQUEST: https://auth.tesla.com/oauth2/v3/token?
METHOD: POST
REQUEST HEADERS: [
"Content-Type": "application/json"
"Authorization": "Bearer … »
"User-Agent": "TeslaSwift"
]
REQUEST BODY: {
  "client_id" : "ownerapi",
  "code" : « … »,
  "redirect_uri" : "https:\/\/auth.tesla.com\/void\/callback",
  "code_verifier" : « … »,
  "client_secret" : « … »,
  "grant_type" : "authorization_code"
}
2021-04-20 14:26:04.380624+0200 Tesla1[5507:1729826] [Process] 0x14a81a818 - [pageProxyID=56, webPageID=57, PID=5516] WebPageProxy::didFailProvisionalLoadForFrame: frameID = 3, domain = WebKitErrorDomain, code = 102

RESPONSE: Optional(https://auth.tesla.com/oauth2/v3/token?)
STATUS CODE: 200
HEADERS: [
"x-response-time": "81.699ms"
"x-dns-prefetch-control": "off"
"Content-Encoding": "gzip"
"Content-Type": "application/json"
"Pragma": "no-cache"
"x-xss-protection": "1; mode=block"
"Date": "Tue, 20 Apr 2021 12:26:04 GMT"
"Server": "nginx"
"x-request-id": « … »
"Strict-Transport-Security": "max-age=15552000; includeSubDomains"
"x-correlation-id": « … »
"Content-Length": "2330"
"Cache-Control": "no-store"
"x-content-type-options": "nosniff"
"x-edgeconnect-origin-mex-latency": "161"
"x-download-options": "noopen"
"x-edgeconnect-midmile-rtt": "71"
"x-frame-options": "DENY"
"Vary": "Accept-Encoding"
]

**Comment by Jim3750** [comment]
Well, since more than 48 hours now, the random 403 error on authenticateWeb has totally disappeared, without any code change. I'd appreciate to know if SohrabYY sees the same.

**Comment by SohrabYY** [comment]
I noticed the same. I haven't seen 403 for last few days.

**Comment by Jim3750** [comment]
Looks like a change of behavior (bug correction?) on Tesla side?
