### ISSUE TITLE
Auth for China

### ISSUE THREAD

**Issue by nix1024** [jonasman/TeslaSwift#75]
The auth base URL for Chinese account should be "https://auth.tesla.cn" instead of "https://auth.tesla.com", please added it.

PS: there are some misspellings in the project, maybe you can enable Spelling Check in Xcode.

**Comment by birdmichael** [comment]
+1

**Comment by jonasman** [comment]
How do we know when to connect to china or not?
I can add a parameter to the auth method

**Comment by birdmichael** [comment]
I think it can be enumerated as authorized countries.

**Comment by wongzigii** [comment]
In fact, you can check if It is an oversea user or not in 'didReceiveServerRedirectForProvisionalNavigation' method during the 302 redirecting.

**Comment by RSickenberg** [comment]
+1

**Comment by RSickenberg** [comment]
Hey @jonasman, may I can try to help you with this? 

I would like to push an update for https://teslacompanion.app/ but if this issue is still there, it will annoy me 🥲

**Comment by jonasman** [comment]
Sure, can you add the setting as a parameter? i didn't have time to look into this yet

**Comment by RSickenberg** [comment]
Okay it's fixed on my side (maybe quick and dirty but it's working) 🎉

**Comment by jonasman** [comment]
This is already on the lib, closing
