### ISSUE TITLE
getVehicles: authenticationRequired

### ISSUE THREAD

**Issue by teslapilotlog** [jonasman/TeslaSwift#79]
Post the earlier issue on error 403, I am now hitting a new problem. 
After a successful api.athenticateWeb, as long as the token is valid (5mn) all other kind of api calls go OK.
However, after 5mn, api.getVehicles goes in error with « authenticationRequired ».
Not sure how to treat this case.

**Comment by jonasman** [comment]
The api should get a new token by itself. Isn’t it working for you?

**Comment by Jim3750** [comment]
This can be closed; same as "Error 403" error.
