### ISSUE TITLE
How to save the user

### ISSUE THREAD

**Issue by perteadrian** [jonasman/TeslaSwift#8]
First, thanks for the library. 
How can I retain the user once he is logged in. So the second time when he'll open the app, he is already logged in. 
I saw that the library handles itself the authToken change itself which is nice.

**Comment by jonasman** [comment]
Hi,

You need to store the auth token class using the keychain or some secure method.

Then you need to pass the auth token to the lib in the authentican method.

Sent from my iPhone

On 11 Feb 2017, at 03:25, perteadi <notifications@github.com<mailto:notifications@github.com>> wrote:


First, thanks for the library.
How can I retain the user once he is logged in. So the second time when he'll open the app, he is already logged in.
I saw that the library handles itself the authToken change itself which is nice.

**Comment by perteadrian** [comment]
So, basically, first time I log in the user I should save the auth token in keychain and the second time I log the user I should use the ```.reuse``` with the auth token from keychain?

**Comment by jonasman** [comment]
exactly

**Comment by perteadrian** [comment]
thank you very much.
