### ISSUE TITLE
`getAllData` fails on watchOS with `TeslaError.failedToParseData`

### ISSUE THREAD

**Issue by SohrabYY** [jonasman/TeslaSwift#81]
On some watchOS devices, `getAllData` fails with `TeslaError.failedToParseData` error. 
The same call works fine on the same vehicle on iPhone app but Apple Watch fails.
Any idea why that would happen?
Tested devices: Apple Watch series 6 and 4

**Comment by jonasman** [comment]
Production app or test? if test app, make a clean build and download the latest version of the lib

**Comment by SohrabYY** [comment]
It's on production app. I'm using the latest version of the library though.
It seems like the `teslaJSONDecoder` fails to decode the `ReturnType.self` from `Endpoint.allStates` type

**Comment by SohrabYY** [comment]
@jonasman any suggestions on this?

**Comment by jonasman** [comment]
I have this working on apple watch.
Are you decoding something stored or fresh from the server?

Sent from my iPhone

On 24 Apr 2021, at 16:12, Sohrab ***@***.***> wrote:

﻿

@jonasman<https://github.com/jonasman> any suggestions on this?

**Comment by SohrabYY** [comment]
I'm not, everything is fresh from server. I have this working as well, it just doesn't work on some random devices and it's consistently not working on those devices.

**Comment by jonasman** [comment]
Unless those cars are using some older or newer API that is not compatible with the object. Do you know the api version from the cars?

Sent from my iPhone

On 24 Apr 2021, at 16:41, Sohrab ***@***.***> wrote:

﻿

I'm not, everything is fresh from server. I have this working as well, it just doesn't work on some random devices and it's consistently not working on those devices.

**Comment by SohrabYY** [comment]
The strange part of this is the exact same calls for same data(same account and vehicle) works on the iPhone version, but when it comes to watch, it can't parse it and fails.

**Comment by SohrabYY** [comment]
And this also only happens when calls for `getAllData`, which has pretty bigger response. The other calls for example `getLocationInfo` parses fine

**Comment by SohrabYY** [comment]
@jonasman can `superWorkaround = "super"` in the `VehicleExtended` cause the problem?

**Comment by SohrabYY** [comment]
I'm still facing this issue and I can't find anything that would make difference between watchOS and iOS in terms of parsing the data for `VehicleExtended`

@jonasman aren't you suspected to any properties in this class that would cause the issue?

**Comment by jonasman** [comment]
Unless this is a bug on JSONParsing on Apple side, i don't know what is the cause.

The super workaround could be the cause yes, but it works on my watch.. so very strange.

**Comment by SohrabYY** [comment]
May I know why we have the `super` key in there and what is the risk of removing it?

**Comment by jonasman** [comment]
this key is to get the super class `Vehicle` decoder

**Comment by SohrabYY** [comment]
I finally found the reason for this. The user Id in newer cars seems doesn't feet in `Int` in watchOS.

**Comment by kenmaz** [comment]
Please review this PR
https://github.com/jonasman/TeslaSwift/pull/87
