### ISSUE TITLE
Cannot activate Mock server

### ISSUE THREAD

**Issue by Jim3750** [jonasman/TeslaSwift#82]
I am close to posting my app on AppStore; Apple is requiring login info to test app ( in this case Tesla login).

So far, I have tested the app on my own Tesla account, and I'd prefer not to give my credentials to Apple.

Could this be resolved by the "mock server"? So far, even if I put "api.useMockServer = true" in AppDelegate, I see no change in app behavior (I still need to enter my own credentials). 

What do I miss?

**Comment by jonasman** [comment]
What i do is to add a fake username “test”, “test” and all the server answers are mocked.

Sent from my iPhone

On 24 Apr 2021, at 15:49, Jim3750 ***@***.***> wrote:

﻿

I am close to posting my app on AppStore; Apple is requiring login info to test app ( in this case Tesla login).

So far, I have tested the app on my own Tesla account, and I'd prefer not to give my credentials to Apple.

Could this be resolved by the "mock server"? So far, even if I put "api.useMockServer = true" in AppDelegate, I see no change in app behavior (I still need to enter my own credentials).

What do I miss?
