### ISSUE TITLE
How to logout?

### ISSUE THREAD

**Issue by Jim3750** [jonasman/TeslaSwift#83]
Looking at implementing a "logout" function, which would lead to have the next call of "api.authenticateWeb" ending up with the Tesla login screen. 
Tried few things (accessToken = " "; revoke token - it fails) but unsuccessful so far.

**Comment by jonasman** [comment]
Did you solve the issue?

**Comment by Jim3750** [comment]
Thank you for asking. I had also tried api.logout without success, but I retried just now and... it works!
