### ISSUE TITLE
How to use MFA web login in a SwiftUI view

### ISSUE THREAD

**Issue by NMolargik** [jonasman/TeslaSwift#84]
Hello,
I am not super familiar with UIKit, and I am trying to learn SwiftUI by building a Tesla app to control my car. 
I can no longer get past the authentication stage and this seems to be due to the new necessity to use MFA.

Can anyone provide me with a bit of code showing how to get a web login view working using SwiftUI?
I am not sure how to use the sample code provided.

Any help would be much appreciated, I am currently stuck.
Thanks!

**Comment by jonasman** [comment]
You need to wrap it in a swift ui view. Google for how to use a webview with swiftui.


Sent from my iPhone

On 2 May 2021, at 21:09, NMolargik ***@***.***> wrote:

﻿

Hello,
I am not super familiar with UIKit, and I am trying to learn SwiftUI by building a Tesla app to control my car.
I can no longer get past the authentication stage and this seems to be due to the new necessity to use MFA.

Can anyone provide me with a bit of code showing how to get a web login view working using SwiftUI?
I am not sure how to use the sample code provided.

Any help would be much appreciated, I am currently stuck.
Thanks!

**Comment by NMolargik** [comment]
Do you have any more context? I can't seem to get anything to work or form an understanding using the sample code.

**Comment by NMolargik** [comment]
Do you have a bit more context? I researched webviews in SwiftUI last night and I’m still not seeing how to use this code. It’s not just a url to  pass in. 

Obviously my fault for not being familiar with uikit.
Thanks

**Comment by brianramirez** [comment]
@NMolargik You can create a view controller that conforms to the `UIViewControllerRepresentable` protocol in SwiftUI to present the web login from a SwifUI View. For example:

```swift
struct TeslaLoginView: UIViewControllerRepresentable {
    func makeUIViewController(context: Context) -> UIViewController {
        let auth = TeslaSwift().authenticateWeb { authResult in
            switch authResult {
            case .success(let token):
                // Do something with the token
            case .failure(let error):
                // Do something with the error
            }
        }
        guard let teslaAuthController = auth else { return UIViewController() }
        return authController
    }

    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {
        // Update ViewController in response to SwiftUI state changes...
    }
}
```
Then present it like normal from your SwiftUI View:

```swift
struct MyView: View {
    @State var showLoginView = false

    var body: some View {
        Button("Login") {
            self.showLoginView = true
        }.sheet(isPresented: $showLoginView) {
            TeslaLoginView() // This is the wrapped UIViewController
        }
    }
}
```

You may need to add a "Coordinator" or SwiftUI binding if you need/want to pass data between the two views or handle any delegates.

Hope this helps.

**Comment by NMolargik** [comment]
Okay wow that makes much more sense. Thank you so much!
