### ISSUE TITLE
OAuth authentication broken on initial request

### ISSUE THREAD

**Issue by Kemmey** [jonasman/TeslaSwift#85]
Hey João, 

This morning it seems Tesla made some changes to their authentication servers yet again - breaking the common OAuth implementation. 

It's broken in my apps, and it's broken in the apps that I know use this library. As well as Remote S and possibly others. 

Just a heads up!

I was browsing through the Tim Dorr repo discussions, but was unable to find anything actionable :-(

Regards, 

Kim

**Comment by jonasman** [comment]
Thanks for the heads up!
Lets try to fix it asap

Sent from my iPhone

On 9 May 2021, at 11:32, Kim Hansen ***@***.***> wrote:

﻿

Hey João,

This morning it seems Tesla made some changes to their authentication servers yet again - breaking the common OAuth implementation.

It's broken in my apps, and it's broken in the apps that I know use this library. As well as Remote S and possibly others.

Just a heads up!

I was browsing through the Tim Dorr repo discussions, but was unable to find anything actionable :-(

Regards,

Kim

**Comment by Kemmey** [comment]
NP

Been banging on it for a few minutes this morning - but have family obligations today! (Am in CET time zone)

I tried new user agent string - no luck. I tried to change tls to 1.2, but couldn't figure out how to do that. 

I tried changing "state" param - no dice

**Comment by Kemmey** [comment]
I see some mention of sha256 being upped to 512? So possibly the code challenge needs to be updated

**Comment by Kemmey** [comment]
FYI - official app is broken too, now. 

Don't logout to verify - you'll lose access to your car like I did :-D

**Comment by Kemmey** [comment]
Hey @jonasman - login seems to have been restored from Tesla's end now!

**Comment by jonasman** [comment]
hah great :)
