### ISSUE TITLE
api.logout does not logout

### ISSUE THREAD

**Issue by Jim3750** [jonasman/TeslaSwift#86]
About to post my app, I made a new test of logout (I use api.logout).

What I am expecting: after logout, a new api.authenticateWeb should end up with the Tesla web login screen.

What I get: after logout, api.authenticateWeb goes thru without re-asking for Tesla login,  which means I am not logged-out.

What do I miss?

(I closed the same issue earlier,  because I got effectively logged-out, but it occurred only one time, probably caused by some other reason)

**Comment by jonasman** [comment]
That’s because the web view is caching the authentication.

**Comment by Jim3750** [comment]
Is there a way to empty the cache?

**Comment by jonasman** [comment]
you need to clean safari cache i think

**Comment by Jim3750** [comment]
cleaning of safari cache ("clean history and website data") has no effect on the issue.

**Comment by jonasman** [comment]
Maybe it is the cookies? I need to look into this

**Comment by jonasman** [comment]
Fixed on the master: https://github.com/jonasman/TeslaSwift/commit/b52d2ee8646d61b6150fdfe7e274a52c196f0728
