### ISSUE TITLE
"Pilot Log for Tesla" is in App Store

### ISSUE THREAD

**Issue by Jim3750** [jonasman/TeslaSwift#89]
You can add "Pilot Log for Tesla" to the list of apps using TeslaSwift.

Thank you very much for your support during the development.

**Comment by jonasman** [comment]
Hi, do you wanna do a PR?

**Comment by Jim3750** [comment]
Nothing significative changed, so no PR.

**Comment by jonasman** [comment]
To add your app to the list

Sent from my iPhone

On 25 Jun 2021, at 09:13, Jim3750 ***@***.***> wrote:

﻿

Nothing significative changed, so no PR.

**Comment by Jim3750** [comment]
Sorry, beginner enough not to know how to do this.

**Comment by jonasman** [comment]
Just open a PR for the readme file
