### ISSUE TITLE
Error Code 540

### ISSUE THREAD

**Issue by corear** [jonasman/TeslaSwift#90]
I have just recently encountered error code 540 after attempting to get any information on a specific vehicle after waking it up. What is the correct protocol to fix this vague error?

**Comment by jonasman** [comment]
you can do PR :)

**Comment by corear** [comment]
I just didn't know if this was an issue that I could fix on my own or not.

**Comment by corear** [comment]
I am unsure how to solve this error code, as well as unsure what the code means in general. I think it may be a hierarchy issue, but I just do not know. Any suggestions?
