### ISSUE TITLE
Stay logged in

### ISSUE THREAD

**Issue by pinloop** [jonasman/TeslaSwift#94]
Each time I fully close the app or rebuild in Xcode I'll have to re-rolgin each time. Is there any time to "stay logged in"?

As per now, I'll have to open the app, the press login a wait a few seconds for the authentication, and then wait for the API to get my car, and then go to the car in the table view, and then be able to control the car with commands. This takes some time. The users would want to do this fast. Any suggestions?

**Comment by jonasman** [comment]
Yes, use the api reuse token function
