### ISSUE TITLE
Display vehicle unavailable

### ISSUE THREAD

**Issue by leiat22** [jonasman/TeslaSwift#96]
I am using this code to unlock the doors for the car:

```
func commandUnlockDoors() {
    if let vehicle = vehicle {
        _ = api.sendCommandToVehicle(vehicle, command: .unlockDoors).done {
            (response:CommandResponse) -> Void in
            self.responseView.text = (response.result! ? "true" : "false")
            if let reason = response.reason {
                self.responseView.text.append(reason)
            }
        }
    }
}
```

If the code successfully works, it says `true` inside the `responseView`.
When the car is for example sleeping, I can see this message in the print log:
`RESPONSE BODY ERROR: {"response":null,"error":"vehicle unavailable: {:error=>\"vehicle unavailable:\"}","error_description":""}`

Basically I want to display a message if the the action did not go through.

How can I also display that message in the `responseView` if it occurs?

**Comment by leiat22** [comment]
@jonasman ?

**Comment by jonasman** [comment]
your code seems ok

**Comment by leiat22** [comment]
> your code seems ok

How can I check if the action did not go through?

**Comment by jonasman** [comment]
response.result == false ?

**Comment by leiat22** [comment]
> response.result == false ?

That just displays false, I want to display the error message

**Comment by jonasman** [comment]
you need to use the promise error case maybe

**Comment by leiat22** [comment]
> you need to use the promise error case maybe

How would that look like? Can you provide an example please?

**Comment by jonasman** [comment]
use the catch function
docs here: https://github.com/mxcl/PromiseKit

**Comment by leiat22** [comment]
> use the catch function
> docs here: https://github.com/mxcl/PromiseKit

Ok. Just a question, is the `if let reason = response.reason {` necessary?

**Comment by jonasman** [comment]
if it is an optional i guess so
