### ISSUE TITLE
Runs "if (!api.isAuthenticated)" even if my cars gets fetched

### ISSUE THREAD

**Issue by leiat22** [jonasman/TeslaSwift#99]
So I have this issue. Also when running it on the example project.

When building and running the example app after a 1 day, it asks me to login, because of the following code in `TabController.swift`:

```
override func viewDidAppear(_ animated: Bool) {
		super.viewDidAppear(animated)
		
		if (!api.isAuthenticated) {
			
			performSegue(withIdentifier: "loginSegue", sender: self)
			
		}
	}
```

If I remove this part: `performSegue(withIdentifier: "loginSegue", sender: self)` , it skips the login part, and shows me my vehicles. Why does it ask me to login, even if the cars already is there?

**Comment by leiatNeedsToStopSpamming** [comment]
It's not @jonasman's responsibility to teach you how to program in Swift, please stop spamming issues

**Comment by leiat22** [comment]
> It's not @jonasman's responsibility to teach you how to program in Swift, please stop spamming issues. This repo is pretty small, if you don't understand what "isAuthenticated" is doing, go read the code. Learning how to solve these tasks yourself will be invaluable for you.

Stop creating multiple accounts. If you want to make a comment, do it with your main account.

**Comment by jonasman** [comment]
@leiat22 unfortunately he is right. You should take some Swift course somewhere and use this repo for library questions not swift programming

**Comment by leiat22** [comment]
> @leiat22 unfortunately he/she is right. You should take some Swift course somewhere and use this repo for library questions not swift programming

Well, the issue is still with the API...
